name: Deploy Jekyll Site to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - ghpages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Ensure Gemfile exists or create one
      run: |
        if [ ! -f Gemfile ]; then
          echo "Gemfile not found. Creating a default Gemfile."
          cat <<EOL > Gemfile
          source "https://rubygems.org"
          gem "jekyll"
          EOL
        fi

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: bundle install

    - name: Build Jekyll site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        publish_branch: deploy/github-page
